version: "3.8"
services: 
  pgres:
    image: postgres
    restart: always
    environment: 
      POSTGRES_USER: hami
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: hanzi
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    command: postgres -c listen_addresses=*
  redis:
    image: redis:alpine
    volumes: 
      - ./data/redis:/var/lib/redis/data
    ports:
      - "6379:6379"
  web: 
    build:
      context: .
      target: dev
    image: hanzi
    depends_on: 
      - pgres
      - redis
    ports: 
      - "4000:4000"
    environment: 
      DB_HOST: postgres://hami:postgres@pgres:5432/hanzi
    command: ["./wait-for-it.sh", "redis:6379", "pgres:5432","--timeout=35","--", "npm", "start"]
    

